spring:
  application:
    name: cat-parser
  servlet:
    multipart:
      max-file-size: 40MB
      max-request-size: 40MB
  cassandra:
    schema-action: CREATE_IF_NOT_EXISTS
    request:
      timeout: 10s
    connection:
      connect-timeout: 10s
      init-query-timeout: 10s
    contact-points: localhost
    port: 9042
    keyspace-name: spring_cassandra
    username: cassandra
    password: cassandra
    local-datacenter: datacenter1
server:
  servlet:
    contextPath: /api-cat

parallel-execution:
  fork-join:
    enabled: false
    pools: 100
    workload: 2000
  executor-service:
    enabled: false
    pools: 100
    virtual: true

logging:
  level:
    org:
      springframework:
        aop:
          interceptor:
            PerformanceMonitorInterceptor: TRACE