services:
  cassandra:
    image: cassandra:4.1.0
    environment:
      - CASSANDRA_USER=myuser
      - CASSANDRA_PASSWORD=mypassword
      - CASSANDRA_PORT=9042
      - CASSANDRA_CLUSTER_NAME=test
    ports:
      - "9042:9042"
      - "7000:7000"
  init-script:
    image: cassandra:4.1.0
    depends_on:
      - cassandra # IMPORTANT: this init container can only start up after the original container is started
    restart: "no" # IMPORTANT: the restart should be set to "no" so that the init container is used only once after the original container is started
    entrypoint: [ "/init.sh" ] # executing the init script
    volumes:
      - ./cassandra-init-data.sh:/init.sh # the init script is added via volumes